<?php
/**
 * @file
 * Code for the gsb_feature_academic_calendar_ct feature.
 */

include_once 'gsb_feature_academic_calendar_ct.features.inc';

const GSB_FEATURE_ACADEMIC_CALENDAR = '10556';

/**
 * Implements hook_form_FORM_ID_alter() for academic_calendar_event_node_form().
 */
function gsb_feature_academic_calendar_ct_form_academic_calendar_event_node_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['field_event_category'])) {
    $langcode = $form['field_event_category']['#language'];
    $form['field_event_category'][$langcode]['#value'] = GSB_FEATURE_ACADEMIC_CALENDAR;
    $form['field_event_category'][$langcode]['#type'] = 'hidden';
  }
}

/**
 * Implements hook_date_popup_process_alter().
 */
function gsb_feature_academic_calendar_ct_date_popup_process_alter(&$element, &$form_state, $context) {
  if ($form_state['build_info']['form_id'] != 'academic_calendar_event_node_form') {
    return;
  }

  if (isset($element['#field']['field_name']) && $element['#field']['field_name'] == 'field_event_date') {
    $element['time']['#value'] = '00:00';
    $element['time']['#default_value'] = '00:00';
    $element['time']['#type'] = 'hidden';
  }
}
